
GET http://localhost:3003/api/authors
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtsaW1rb2RpbWFAdHV0LmJ5IiwibmFtZSI6IkFydG8gSGVsbGFzMTIiLCJpZCI6NCwiaWF0IjoxNjQyOTI1MjQ2LCJleHAiOjE2NDM3ODkyNDZ9.pootdxE0-Lgvz4SXNOtlrSxh1ov5PQ-B9xsKmDAfup8
