GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

  {
    "username": "klimkodima@tut.by",
    "name": "Arto Hellas",
    "password": "secret"
  }

###
GET http://localhost:3003/api/users/1

###
GET http://localhost:3003/api/users/1?read=true

###
GET http://localhost:3003/api/users/1?read=false

###
PUT http://localhost:3003/api/users/klimkodima@tut.by
content-type: application/json

  {
    "username": "klimkodima@tut.by",
    "name": "Arto Hellas",
    "password": "secret"
  }

###
DELETE http://localhost:3003/api/users/5

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

  {
    "username": "klimkodima",
    "name": "Arto Hellas12",
    "password": "secret"
  }

